//;*****************************************************************;
//;*****************************************************************;
//;**                                                             **;
//;**     (C) COPYRIGHT American Megatrends Inc. 2008-2013        **;
//;**                     ALL RIGHTS RESERVED                     **;
//;**                                                             **;
//;**  This computer software, including display screens and      **;
//;**  all related materials, are confidential and the            **;
//;**  exclusive property of American Megatrends, Inc.  They      **;
//;**  are available for limited use, but only pursuant to        **;
//;**  a written license agreement distributed with this          **;
//;**  computer software.  This computer software, including      **;
//;**  display screens and all related materials, shall not be    **;
//;**  copied, reproduced, published or distributed, in whole     **;
//;**  or in part, in any medium, by any means, for any           **;
//;**  purpose without the express written consent of American    **;
//;**  Megatrends, Inc.                                           **;
//;**                                                             **;
//;**                                                             **;
//;**                American Megatrends, Inc.                    **;
//;**           5555 Oakbook Parkway, Building 200                **;
//;**     Norcross,  Georgia - 30071, USA. Phone-(770)-246-8600.  **;
//;**                                                             **;
//;*****************************************************************;
//;*****************************************************************;

// File Name  : sensortype_str.js
// Brief      : sensortype page string table
// Author Name:

eLang.sensortype_strings = new Array();
eLang.sensortype_strings[0] = "保留";
eLang.sensortype_strings[1] = "溫度";
eLang.sensortype_strings[2] = "電壓";
eLang.sensortype_strings[3] = "目前";
eLang.sensortype_strings[4] = "風扇";
eLang.sensortype_strings[5] = "物理安全性（Chassis Instruction）";
eLang.sensortype_strings[6] = "平臺安全性的違規嘗試";
eLang.sensortype_strings[7] = "處理器";
eLang.sensortype_strings[8] = "電源";
eLang.sensortype_strings[9] = "電源單元";
eLang.sensortype_strings[10] = "冷卻裝置";
eLang.sensortype_strings[11] = "其它基於單位的感應器";
eLang.sensortype_strings[12] = "記憶體";
eLang.sensortype_strings[13] = "磁碟機插槽 （Bay）";
eLang.sensortype_strings[14] = "POST Memory 重新調整大小";
eLang.sensortype_strings[15] = "BIOS POST 進度";
eLang.sensortype_strings[16] = "停用事件日誌";
eLang.sensortype_strings[17] = "WatchDog 1";
eLang.sensortype_strings[18] = "系統事件";
eLang.sensortype_strings[19] = "關鍵中斷";
eLang.sensortype_strings[20] = "Button / Switch";
eLang.sensortype_strings[21] = "Module / Board";
eLang.sensortype_strings[22] = "Microcontroller / Coprocessor";
eLang.sensortype_strings[23] = "Add-in Card";
eLang.sensortype_strings[24] = "Chassis";
eLang.sensortype_strings[25] = "Chip Set";
eLang.sensortype_strings[26] = "其他 FRU";
eLang.sensortype_strings[27] = "Cable / Interconnect";
eLang.sensortype_strings[28] = "Terminator";
eLang.sensortype_strings[29] = "System Boot / Restart Initiated";
eLang.sensortype_strings[30] = "Boot Error";
eLang.sensortype_strings[31] = "OS Boot";
eLang.sensortype_strings[32] = "作業系統停止 / 關機";
eLang.sensortype_strings[33] = "插槽 / 連接器";
eLang.sensortype_strings[34] = "系統 ACPI 電源狀態";
eLang.sensortype_strings[35] = "WatchDog 2";
eLang.sensortype_strings[36] = "平臺警報";
eLang.sensortype_strings[37] = "實體存在";
eLang.sensortype_strings[38] = "監視器 ASIC / IC";
eLang.sensortype_strings[39] = "LAN";
eLang.sensortype_strings[40] = "管理子系統運行狀況";
eLang.sensortype_strings[41] = "電池";
eLang.sensortype_strings[42] = "Session 審計";
eLang.sensortype_strings[43] = "版本變更";
eLang.sensortype_strings[44] = "FRU 狀態";
eLang.sensortype_strings[240] = "FRU 熱插拔";
eLang.sensortype_strings[241] = "IPMB-0 狀態";
eLang.sensortype_strings[242] = "模組熱插拔";
eLang.sensortype_strings[192] = "OEM";