//;*****************************************************************;
//;*****************************************************************;
//;**                                                             **;
//;**     (C) COPYRIGHT American Megatrends Inc. 2008-2013        **;
//;**                     ALL RIGHTS RESERVED                     **;
//;**                                                             **;
//;**  This computer software, including display screens and      **;
//;**  all related materials, are confidential and the            **;
//;**  exclusive property of American Megatrends, Inc.  They      **;
//;**  are available for limited use, but only pursuant to        **;
//;**  a written license agreement distributed with this          **;
//;**  computer software.  This computer software, including      **;
//;**  display screens and all related materials, shall not be    **;
//;**  copied, reproduced, published or distributed, in whole     **;
//;**  or in part, in any medium, by any means, for any           **;
//;**  purpose without the express written consent of American    **;
//;**  Megatrends, Inc.                                           **;
//;**                                                             **;
//;**                                                             **;
//;**                American Megatrends, Inc.                    **;
//;**           5555 Oakbook Parkway, Building 200                **;
//;**     Norcross,  Georgia - 30071, USA. Phone-(770)-246-8600.  **;
//;**                                                             **;
//;*****************************************************************;
//;*****************************************************************;

// File Name  : unittype_str.js
// Brief      : unittype page string table
// Author Name:
/****************************** Unit type codes ********************************/
//eLang.unittype_strings[UNIT TYPE CODE] = "UNIT TYPE";
/**************************************************************************************/
eLang.unittype_strings = new Array();
eLang.unittype_strings[0] = " ";
eLang.unittype_strings[1] = "&deg; C";
eLang.unittype_strings[2] = "&deg; F";
eLang.unittype_strings[3] = "&deg; K";
eLang.unittype_strings[4] = "伏特";
eLang.unittype_strings[5] = "安培";
eLang.unittype_strings[6] = "瓦特";
eLang.unittype_strings[7] = "焦耳";
eLang.unittype_strings[8] = "庫侖";
eLang.unittype_strings[9] = "VA";
eLang.unittype_strings[10] = "Nits";
eLang.unittype_strings[11] = "流明";
eLang.unittype_strings[12] = "勒克斯";
eLang.unittype_strings[13] = "坎德拉";
eLang.unittype_strings[14] = "kPa";
eLang.unittype_strings[15] = "PSI";
eLang.unittype_strings[16] = "牛頓";
eLang.unittype_strings[17] = "CFM";
eLang.unittype_strings[18] = "RPM";
eLang.unittype_strings[19] = "Hz";
eLang.unittype_strings[20] = "微秒 (microsecond)";
eLang.unittype_strings[21] = "毫秒 (millisecond)";
eLang.unittype_strings[22] = "second";
eLang.unittype_strings[23] = "分鐘";
eLang.unittype_strings[24] = "小時";
eLang.unittype_strings[25] = "一天";
eLang.unittype_strings[26] = "周";
eLang.unittype_strings[27] = "mil";
eLang.unittype_strings[28] = "inches";
eLang.unittype_strings[29] = "feet";
eLang.unittype_strings[30] = "cu in";
eLang.unittype_strings[31] = "cu feet";
eLang.unittype_strings[32] = "mm";
eLang.unittype_strings[33] = "cm";
eLang.unittype_strings[34] = "m";
eLang.unittype_strings[35] = "cu cm";
eLang.unittype_strings[36] = "cu m";
eLang.unittype_strings[37] = "公升";
eLang.unittype_strings[38] = "fluid ounce";
eLang.unittype_strings[39] = "（角度）radians";
eLang.unittype_strings[40] = "（立體角）steradians";
eLang.unittype_strings[41] = "revolutions";
eLang.unittype_strings[42] = "cycles";
eLang.unittype_strings[43] = "重力";
eLang.unittype_strings[44] = "盎司";
eLang.unittype_strings[45] = "鎊";
eLang.unittype_strings[46] = "ft-lb";
eLang.unittype_strings[47] = "oz-in";
eLang.unittype_strings[48] = "高斯";
eLang.unittype_strings[49] = "gilberts";
eLang.unittype_strings[50] = "henry";
eLang.unittype_strings[51] = "millihenry";
eLang.unittype_strings[52] = "farad";
eLang.unittype_strings[53] = "microfarad";
eLang.unittype_strings[54] = "歐姆";
eLang.unittype_strings[55] = "siemens";
eLang.unittype_strings[56] = "mole";
eLang.unittype_strings[57] = "becquerel";
eLang.unittype_strings[58] = "PPM （parts / 10 萬)";
eLang.unittype_strings[59] = " ";
eLang.unittype_strings[60] = "分貝";
eLang.unittype_strings[61] = "DbA";
eLang.unittype_strings[62] = "DbC";
eLang.unittype_strings[63] = "gray";
eLang.unittype_strings[64] = "sievert";
eLang.unittype_strings[65] = "color temp &deg; K";
eLang.unittype_strings[66] = "bit";
eLang.unittype_strings[67] = "kilobit";
eLang.unittype_strings[68] = "megabit";
eLang.unittype_strings[69] = "gigabit";
eLang.unittype_strings[70] = "byte";
eLang.unittype_strings[71] = "kilobyte";
eLang.unittype_strings[72] = "megabyte";
eLang.unittype_strings[73] = "gigabyte";
eLang.unittype_strings[74] = "word (data)";
eLang.unittype_strings[75] = "dword";
eLang.unittype_strings[76] = "qword";
eLang.unittype_strings[77] = "line";
eLang.unittype_strings[78] = "命中";
eLang.unittype_strings[79] = "沒有命中";
eLang.unittype_strings[80] = "重試";
eLang.unittype_strings[81] = "重置";
eLang.unittype_strings[82] = "overrun/overflow";
eLang.unittype_strings[83] = "underrun";
eLang.unittype_strings[84] = "碰撞";
eLang.unittype_strings[85] = "封包";
eLang.unittype_strings[86] = "訊息";
eLang.unittype_strings[87] = "characters";
eLang.unittype_strings[88] = "錯誤";
eLang.unittype_strings[89] = "可修正的錯誤";
eLang.unittype_strings[90] = "無法修正的錯誤";
