enabled              
encryptedenable      
host                 
hostSecondary        
base
binddn
bindpw              
pam_password         
nss_reconnect_tries  
port                 389
portSecondary
attribute_userlogin  cn
fqdn                 
