#This Ini file is to add memory limits for inidividual process, to avoid OMM killer.
#User has to set all the values according to their test scenarios.
#1 enable monitoring,0-disable monitoring
#main memory lower limit to check
[memory_lower_limit]
memory_lower_limit=10240

[IPMI]
mem_warning_limit=49152
mem_critical_limit=51200
Enable_Monitoring=0

[cdserver]
mem_warning_limit=100
mem_critical_limit=150
Enable_Monitoring=0

[fdserver]
mem_warning_limit=100
mem_critical_limit=150
Enable_Monitoring=0

[webgo]
mem_warning_limit=228484
mem_critical_limit=229484
Enable_Monitoring=0

[qomd]
mem_warning_limit=46080
mem_critical_limit=51200
Enable_Monitoring=0

[smashclpd]
mem_warning_limit=25600
mem_critical_limit=30720
Enable_Monitoring=0
