//;*****************************************************************;
//;*****************************************************************;
//;**                                                             **;
//;**     (C) COPYRIGHT American Megatrends Inc. 2008-2009        **;
//;**                     ALL RIGHTS RESERVED                     **;
//;**                                                             **;
//;**  This computer software, including display screens and      **;
//;**  all related materials, are confidential and the            **;
//;**  exclusive property of American Megatrends, Inc.  They      **;
//;**  are available for limited use, but only pursuant to        **;
//;**  a written license agreement distributed with this          **;
//;**  computer software.  This computer software, including      **;
//;**  display screens and all related materials, shall not be    **;
//;**  copied, reproduced, published or distributed, in whole     **;
//;**  or in part, in any medium, by any means, for any           **;
//;**  purpose without the express written consent of American    **;
//;**  Megatrends, Inc.                                           **;
//;**                                                             **;
//;**                                                             **;
//;**                American Megatrends, Inc.                    **;
//;**           5555 Oakbook Parkway, Building 200                **;
//;**     Norcross,  Georgia - 30071, USA. Phone-(770)-246-8600.  **;
//;**                                                             **;
//;*****************************************************************;
//;*****************************************************************;

/****************************** Sensor type codes ********************************/
//eLang.sensortype_strings[SENSOR TYPE CODE] = "SENSOR TYPE";
/**************************************************************************************/
eLang.sensortype_strings = new Array();
eLang.sensortype_strings[0] = "reserved";
eLang.sensortype_strings[1] = "Temperature";
eLang.sensortype_strings[2] = "Voltage";
eLang.sensortype_strings[3] = "Current";
eLang.sensortype_strings[4] = "Fan";
eLang.sensortype_strings[5] = "Physical Security (Chassis Intrusion)";
eLang.sensortype_strings[6] = "Platform Security Violation Attempt";
eLang.sensortype_strings[7] = "Processor";
eLang.sensortype_strings[8] = "Power Supply";
eLang.sensortype_strings[9] = "Power Unit";
eLang.sensortype_strings[10] = "Cooling Device";
eLang.sensortype_strings[11] = "Other Units-based sensor";
eLang.sensortype_strings[12] = "Memory";
eLang.sensortype_strings[13] = "Drive Slot (Bay)";
eLang.sensortype_strings[14] = "POST Memory Resize";
eLang.sensortype_strings[15] = "BIOS POST Progress";
eLang.sensortype_strings[16] = "Event Logging disabled";
eLang.sensortype_strings[17] = "Watchdog 1";
eLang.sensortype_strings[18] = "System Event";
eLang.sensortype_strings[19] = "Critical Interrupt";
eLang.sensortype_strings[20] = "Button / Switch";
eLang.sensortype_strings[21] = "Module / Board";
eLang.sensortype_strings[22] = "Microcontroller / Coprocessor";
eLang.sensortype_strings[23] = "Add-in Card";
eLang.sensortype_strings[24] = "Chassis";
eLang.sensortype_strings[25] = "Chip Set";
eLang.sensortype_strings[26] = "Other FRU";
eLang.sensortype_strings[27] = "Cable / Interconnect";
eLang.sensortype_strings[28] = "Terminator";
eLang.sensortype_strings[29] = "System Boot / Restart Initiated";
eLang.sensortype_strings[30] = "Boot Error";
eLang.sensortype_strings[31] = "OS Boot";
eLang.sensortype_strings[32] = "OS Stop / Shutdown";
eLang.sensortype_strings[33] = "Slot / Connector";
eLang.sensortype_strings[34] = "System ACPI Power State";
eLang.sensortype_strings[35] = "Watchdog 2";
eLang.sensortype_strings[36] = "Platform Alert";
eLang.sensortype_strings[37] = "Entity Presence";
eLang.sensortype_strings[38] = "Monitor ASIC / IC";
eLang.sensortype_strings[39] = "LAN";
eLang.sensortype_strings[40] = "Management Subsystem Health";
eLang.sensortype_strings[41] = "Battery";
eLang.sensortype_strings[42] = "Session Audit";
eLang.sensortype_strings[43] = "Version Change";
eLang.sensortype_strings[44] = "FRU State";
eLang.sensortype_strings[240] = "FRU Hot Swap";
eLang.sensortype_strings[241] = "IPMB-0 Status";
eLang.sensortype_strings[242] = "Module Hot Swap";
eLang.sensortype_strings[192] = "OEM";
eLang.sensortype_strings[193] = "OEM";
eLang.sensortype_strings[194] = "OEM";
eLang.sensortype_strings[195] = "OEM";
eLang.sensortype_strings[196] = "OEM";
eLang.sensortype_strings[197] = "OEM";
eLang.sensortype_strings[198] = "OEM";
eLang.sensortype_strings[199] = "OEM";
eLang.sensortype_strings[200] = "OEM";
eLang.sensortype_strings[201] = "OEM";
eLang.sensortype_strings[202] = "OEM";
eLang.sensortype_strings[203] = "OEM";
eLang.sensortype_strings[204] = "OEM";
eLang.sensortype_strings[205] = "OEM";
eLang.sensortype_strings[206] = "OEM";
eLang.sensortype_strings[207] = "OEM";
eLang.sensortype_strings[208] = "OEM";
eLang.sensortype_strings[209] = "OEM";
eLang.sensortype_strings[210] = "OEM";
eLang.sensortype_strings[211] = "OEM";
eLang.sensortype_strings[212] = "OEM";
eLang.sensortype_strings[213] = "OEM";
eLang.sensortype_strings[214] = "OEM";
eLang.sensortype_strings[215] = "OEM";
eLang.sensortype_strings[216] = "OEM";
eLang.sensortype_strings[217] = "OEM";
eLang.sensortype_strings[218] = "OEM";
eLang.sensortype_strings[219] = "OEM";
eLang.sensortype_strings[220] = "OEM";
eLang.sensortype_strings[221] = "OEM";
eLang.sensortype_strings[222] = "OEM";
eLang.sensortype_strings[223] = "OEM";
eLang.sensortype_strings[224] = "OEM";
eLang.sensortype_strings[225] = "OEM";
eLang.sensortype_strings[226] = "OEM";
eLang.sensortype_strings[227] = "OEM";
eLang.sensortype_strings[228] = "OEM";
eLang.sensortype_strings[229] = "OEM";
eLang.sensortype_strings[230] = "OEM";
eLang.sensortype_strings[231] = "OEM";
eLang.sensortype_strings[232] = "OEM";
eLang.sensortype_strings[233] = "OEM";
eLang.sensortype_strings[234] = "OEM";
eLang.sensortype_strings[235] = "OEM";
eLang.sensortype_strings[236] = "OEM";
eLang.sensortype_strings[237] = "OEM";
eLang.sensortype_strings[238] = "OEM";
eLang.sensortype_strings[239] = "OEM";
eLang.sensortype_strings[240] = "OEM";
eLang.sensortype_strings[241] = "OEM";
eLang.sensortype_strings[242] = "OEM";
eLang.sensortype_strings[243] = "OEM";
eLang.sensortype_strings[244] = "OEM";
eLang.sensortype_strings[245] = "OEM";
eLang.sensortype_strings[246] = "OEM";
eLang.sensortype_strings[247] = "OEM";
eLang.sensortype_strings[248] = "OEM";
eLang.sensortype_strings[249] = "OEM";
eLang.sensortype_strings[250] = "OEM";
eLang.sensortype_strings[251] = "OEM";
eLang.sensortype_strings[252] = "OEM";
eLang.sensortype_strings[253] = "OEM";
eLang.sensortype_strings[254] = "OEM";
eLang.sensortype_strings[255] = "OEM";
