#! /bin/sh
# /etc/init.d/fdserver: start FD Server
#
# chkconfig: 2345 10 90
#Runlevel : 3 = S35
# Restart the service on warm reboot
#Runlevel : 9 = K35
#Runlevel : 9 = S35


PATH=/bin:/usr/bin:/sbin:/usr/sbin

PATHFUL_FDSERVER=/usr/local/bin/fdserverapp
USB_DRIVERNAME=usbe
ACTION=$1


test -f /usr/local/bin/fdserverapp || exit 0

#check service state with ncml conf
SERVICE_NAME="[fd-media]"
SERVICE_CONF="/conf/ncml.conf"
#check service state if enabled
check_service_enabled()
{
	if [ -f $SERVICE_CONF ];
	then
	
		SERVICE_STATE=`cat $SERVICE_CONF | awk -v val=$SERVICE_NAME '$1 == val, $1 == ""' | 
								   awk 'BEGIN {FS="="} /current_state/ {print $2 }'       | 
								   awk 'NR==1 {print $0}'`

		if [ $SERVICE_STATE == 0 ];
		then
			echo $SERVICE_NAME is disabled
			exit 1
#		else
#			echo $SERVICE_NAME is enabled   
		fi
		  
    else
		echo "$SERVICE_CONF doesn't exist"
    fi
}

# Options for start/restart the daemons
#


#

test -f /var/tmp/licstat/vmapp_nolicense && ACTION=stop
case "$ACTION" in
  start)
    	echo -n "Starting FD Redirection Server: fdserver"
    	start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
    ;;
  stop)
    echo -n "Stopping FD Redirection Server: fdserver"
    start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER --signal 1
    echo "."
    ;;
    reload)
    check_service_enabled
	echo -n "Reloading FD Redirection Server: fdserver"
	start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER --signal 1
	echo "."
	;;
    force-reload)
	$0 reload
	;;
    restart)
	echo -n "Restarting FD Redirection Server: fdserver"
	start-stop-daemon --stop --quiet --retry 5 --oknodo --exec $PATHFUL_FDSERVER --signal 1
	check_service_enabled
	start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
	echo "."
	;;
   *)
    echo "Usage: /etc/init.d/fdserver {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
