
[autorecord]
max_dumps=2
password=
max_time=20
remote_support=0
sharetype=
ipaddr=
domain=
username=
dump_path=
mnt_status=-1
max_size=5767168

[record_boot_crash]
vdo_compression_mode=0x0
vdo_duration=0xa
vdo_quality=0x0
frame_count=0x1

