server.modules              = (
                                "libmodhapi"
						      )
server.upload-dirs = ( "/mnt" )

server.document-root        = "/usr/local/www"
server.pid-file = "/var/run/lighttpd.pid"

# files to check for if .../ is requested
index-file.names            = ( "home.html","index.php", "index.html",
                                "index.htm", "default.htm", "index.html.gz" )

debug.log-request-handling = "enable"
debug.log-state-handling = "enable"
debug.log-request-header="enable"
debug.log-response-header="enable"

server.max-read-idle = 120
server.max-keep-alive-idle = 120


# mimetype mapping
mimetype.assign             = (
  ".gif"          =>      "image/gif",
  ".jpg"          =>      "image/jpeg",
  ".jpeg"         =>      "image/jpeg",
  ".png"          =>      "image/png",
  ".css"          =>      "text/css",
  ".html"         =>      "text/html",
  ".htm"          =>      "text/html",
  ".js"           =>      "text/javascript",
  ".text"         =>      "text/plain",
  ".txt"          =>      "text/plain",
  ".xml"          =>      "text/xml",
  ".elg"      	  =>      "application/x-ibmclog",
  ".jnlp"         =>      "application/x-java-jnlp-file",
  ".gz"	  	  => 	  "application/x-gzip",
  ".tar.gz"	  =>	  "application/x-gzip-compressed-tar"  
 )

#enable ipv6 support
server.use-ipv6 = "enable"
server.socket = "[::]:80"

## bind to port (default: 80)
server.port	= 80

## SSL Engine
$SERVER["socket"] == ":443" {
	ssl.engine = "enable" 
	server.use-ipv6 = "enable"
}


