[rmscd]
name=
image=
ipaddr=
sharetype=
start=0
username=
password=
domain=
success=-1

[rmsfd]
name=
image=
ipaddr=
sharetype=
start=0
username=
password=
domain=
success=-1

[rmshd]
name=
image=
ipaddr=
sharetype=
start=0
username=
password=
domain=
success=-1
