
[web]
active_sessions=128
MinSessionInactivityTimeout=300
secure_port=443
MaxSessionInactivityTimeout=1800
interface_name=bond0
session_timeout=1800
service_name=web
current_state=1
nonscecure_port=80
max_sessions=148

[kvm]
secure_port=2147491230
MaxSessionInactivityTimeout=1800
session_timeout=1800
nonscecure_port=2147491226
active_sessions=128
service_name=kvm
max_sessions=130
interface_name=bond0
current_state=1
MinSessionInactivityTimeout=300

[cd-media]
MaxSessionInactivityTimeout=180
interface_name=bond0
current_state=1
session_timeout=4294967295
nonscecure_port=2147488768
secure_port=2147488772
service_name=cd-media
active_sessions=128
max_sessions=132
MinSessionInactivityTimeout=30

[fd-media]
secure_port=2147488774
interface_name=bond0
service_name=fd-media
current_state=1
max_sessions=132
session_timeout=4294967295
MinSessionInactivityTimeout=30
MaxSessionInactivityTimeout=180
nonscecure_port=2147488770
active_sessions=128

[hd-media]
interface_name=bond0
max_sessions=132
nonscecure_port=2147488771
active_sessions=128
MinSessionInactivityTimeout=30
MaxSessionInactivityTimeout=180
service_name=hd-media
current_state=1
session_timeout=4294967295
secure_port=2147488775

[ssh]
session_timeout=600
interface_name=FFFFFFFFFFFFFFFF
nonscecure_port=4294967295
MinSessionInactivityTimeout=60
secure_port=22
current_state=1
active_sessions=255
MaxSessionInactivityTimeout=1800
service_name=ssh
max_sessions=255

[telnet]
session_timeout=600
interface_name=FFFFFFFFFFFFFFFF
nonscecure_port=23
MinSessionInactivityTimeout=60
service_name=telnet
MaxSessionInactivityTimeout=1800
max_sessions=255
secure_port=4294967295
active_sessions=255
current_state=0

[solssh]
MaxSessionInactivityTimeout=1800
secure_port=4294967295
interface_name=bond0
service_name=solssh
session_timeout=60
max_sessions=255
nonscecure_port=52123
active_sessions=255
MinSessionInactivityTimeout=30
current_state=0

