#!/bin/sh

NSUPDATE_BINARY=/usr/local/bin/nsupdate
NSUPDATE_SCRIPT=/usr/local/bin/nsupdate.sh

METHOD=deregister

INTERFACE=$IFACE

#echo " 05-down-nsupdate : IFACE - $IFACE"
if [ "$IFACE"  == "lo" ]
then
	exit 0
fi

PID_FILE=/var/run/nsupdate.$IFACE.pid
if [ -e "$PID_FILE" ]; then
	PID2KILL=`cat $PID_FILE`
	kill -9 $PID2KILL
	rm -f $PID_FILE
fi

case "$IFACE" in
#Bond with Vlan
  bond*.*)
        BOND_DEV=`echo $IFACE | awk -F. '{ print $1 }'`
  ;;
#Normal Bond Device
  bond*)
        BOND_DEV=$IFACE
  ;;
esac

if [ "$BOND_DEV" != "" ]; then
[ -f /sys/class/net/$BOND_DEV/bonding/slaves ] || exit 0
fi

LINK_STATUS=`/sbin/ethtool $IFACE | grep 'Link detected:' | cut -d: -f2 | awk '{ print $1}'`

if [ "$LINK_STATUS" == "no" ]
then
	echo "Link status:Down."
	exit 0
fi

[ -x $NSUPDATE_BINARY ] || exit 0

[ -f /conf/dns.conf ] || exit 0

. /conf/dns.conf

if [ -z "$DO_DDNS" ]; then
	exit 0
fi

if ! [ "$DO_DDNS" == 'yes'  -o "$DO_DDNS" == 'y' ]; then
	exit 0
fi

IP=`/sbin/ifconfig $IFACE |  grep "inet addr:" | cut -d: -f2 | awk '{ print $1}'`

HOST_NAME=`hostname`

DOMAIN_NAME=`grep "domain" /etc/resolv.conf | awk '{ print $2}' | tail -1`

DNS_IP=`grep "nameserver" /etc/resolv.conf | awk '{ print $2}'`
if [ "$HOST_NAME" == "" ]; then
	echo "NSUPDATE: Cannot $METHOD hostname as it is empty"
    	exit 0
fi
if [ "$DNS_IP" == "" ]; then
	echo "NSUPDATE: Skip update as DNS IP is empty"
    	exit 0
fi

if [ "$DOMAIN_NAME" == "" ]; then
	REGISTER_NAME=$HOST_NAME
else	
	REGISTER_NAME=$HOST_NAME.$DOMAIN_NAME
fi

if [ "$TSIG_AUTH" == 'yes' -o "$TSIG_AUTH" == 'y' ]; then
	TSIG_AUTH=1
else
	TSIG_AUTH=0
fi

#echo "NSUPDATE: $METHOD $REGISTER_NAME  to Address $IP ..."

if ! [ "$SET_FQDN" == 'yes' -o "$SET_FQDN" == 'y' -o "$SET_HOSTNAME" == 'yes' -o "$SET_HOSTNAME" == 'y' ]; then

$NSUPDATE_SCRIPT $METHOD $REGISTER_NAME $IP $DOMAIN_NAME $TSIG_AUTH

fi

# Find if IPv6 address present and deregister the corresponding AAAA record
# Ignore Link-local and router advertsement (RA) addresses

#LINK_LOCAL=`ifconfig eth0 | grep Scope:Link | awk '{print $3}' | cut -d'/' -f1`
#LINK_LOCAL=`ifconfig $IFACE | grep Scope:Link | awk '{print $3}' | cut -d'/' -f1`
#SUFFIX=`echo ${LINK_LOCAL#*::}`

#IPv6=`ifconfig eth0 | grep inet6 | grep -v $SUFFIX | awk '{print $3}' | cut -d'/' -f1`
#if `echo $SUFFIX| grep : >/dev/null`; then
#    IPv6=`ifconfig $IFACE | grep inet6 | grep -v $SUFFIX | awk '{print $3}' | cut -d'/' -f1`
#fi

# Ignoring only Link-local

IPv6=`ifconfig $IFACE | grep inet6 | grep -v Scope:Link | awk '{print $3}' |cut -d'/' -f1`

if [ -z "$IPv6" ]; then
	exit 0
fi
for j in $IPv6; do
	#echo "Deregistering AAAA record for $j"
	$NSUPDATE_SCRIPT $METHOD $REGISTER_NAME $j $DOMAIN_NAME $TSIG_AUTH
done

exit 0
