obj-m += videocap.o
videocap-objs := ast_videocap_module.o ast_videocap_proc.o ast_videocap_mmap.o ast_videocap_ioctl.o ast_videocap_engine.o

ccflags-y += -I$(src)/helper-src
ccflags-y += -DSOC_AST2500
